"""CI-level commit attribution collector.

Runs in GitHub Actions on merge to protected branches (dev/qa/prod).
Classifies commits by parsing commit messages — no git-ai dependency needed.
This is tamper-resistant because developers cannot modify commit messages
after merge (branch protection prevents force-push).
"""

import json
import os
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime


@dataclass
class MergedCommit:
    sha: str
    author: str
    author_email: str
    date: date
    message: str
    lines_added: int = 0
    lines_removed: int = 0
    tool: str = "human"


def classify_commit(message: str) -> str:
    """Classify a commit based on its message. Priority order:

    1. Co-Authored-By trailers (tamper-resistant — part of commit SHA)
    2. Commit message patterns
    """
    msg_lower = message.lower()

    # Co-Authored-By: Claude (added automatically by Claude Code)
    if "co-authored-by:" in msg_lower:
        if "claude" in msg_lower or "anthropic" in msg_lower:
            return "claude"
        if "windsurf" in msg_lower or "codeium" in msg_lower:
            return "windsurf"
        if "cursor" in msg_lower:
            return "cursor"
        if "copilot" in msg_lower or "github" in msg_lower:
            return "copilot"

    # Commit message patterns
    if "generated by windsurf" in msg_lower or "[windsurf]" in msg_lower:
        return "windsurf"
    if "generated by cursor" in msg_lower:
        return "cursor"

    return "human"


def get_merge_commits(base_sha: str, head_sha: str) -> list[MergedCommit]:
    """Get all commits between base and head (the commits being merged)."""
    log_format = "%H%x00%an%x00%ae%x00%aI%x00%B%x00"
    separator = "%x01"

    result = subprocess.run(
        [
            "git", "log",
            f"--format={separator}{log_format}",
            "--numstat",
            f"{base_sha}..{head_sha}",
        ],
        capture_output=True,
        text=True,
        timeout=120,
    )

    if result.returncode != 0:
        print(f"Error reading git log: {result.stderr}", file=sys.stderr)
        return []

    commits = []
    for entry in result.stdout.split("\x01"):
        entry = entry.strip()
        if not entry:
            continue

        parts = entry.split("\x00", 5)
        if len(parts) < 5:
            continue

        sha, author, email, date_str, message = (
            parts[0].strip(),
            parts[1].strip(),
            parts[2].strip(),
            parts[3].strip(),
            parts[4].strip(),
        )

        remaining = parts[5] if len(parts) > 5 else ""
        added = 0
        removed = 0
        for line in remaining.strip().splitlines():
            nums = line.split("\t")
            if len(nums) >= 2:
                try:
                    added += int(nums[0])
                except ValueError:
                    pass
                try:
                    removed += int(nums[1])
                except ValueError:
                    pass

        try:
            dt = datetime.fromisoformat(date_str)
            commit_date = dt.date()
        except (ValueError, TypeError):
            continue

        tool = classify_commit(message)

        commits.append(MergedCommit(
            sha=sha,
            author=author,
            author_email=email,
            date=commit_date,
            message=message,
            lines_added=added,
            lines_removed=removed,
            tool=tool,
        ))

    return commits


def build_summary(repo: str, branch: str, commits: list[MergedCommit]) -> dict:
    """Build a JSON summary of the merge for downstream processing."""
    by_tool = defaultdict(lambda: {
        "commits": 0,
        "lines_added": 0,
        "lines_removed": 0,
        "authors": set(),
    })

    for c in commits:
        by_tool[c.tool]["commits"] += 1
        by_tool[c.tool]["lines_added"] += c.lines_added
        by_tool[c.tool]["lines_removed"] += c.lines_removed
        by_tool[c.tool]["authors"].add(c.author)

    summary = {
        "repo": repo,
        "branch": branch,
        "collected_at": datetime.utcnow().isoformat(),
        "total_commits": len(commits),
        "breakdown": {},
        "commits": [],
    }

    for tool, stats in by_tool.items():
        summary["breakdown"][tool] = {
            "commits": stats["commits"],
            "lines_added": stats["lines_added"],
            "lines_removed": stats["lines_removed"],
            "unique_authors": len(stats["authors"]),
        }

    for c in commits:
        summary["commits"].append({
            "sha": c.sha,
            "author": c.author,
            "date": c.date.isoformat(),
            "tool": c.tool,
            "lines_added": c.lines_added,
            "lines_removed": c.lines_removed,
        })

    return summary


def main():
    # Read from GitHub Actions environment
    repo = os.environ.get("GITHUB_REPOSITORY", "unknown")
    branch = os.environ.get("GITHUB_REF_NAME", "unknown")
    base_sha = os.environ.get("BASE_SHA", "")
    head_sha = os.environ.get("HEAD_SHA", "HEAD")
    output_file = os.environ.get("OUTPUT_FILE", "metrics_output.json")

    if not base_sha:
        # Fallback: get the merge base from the event
        event_path = os.environ.get("GITHUB_EVENT_PATH", "")
        if event_path and os.path.exists(event_path):
            with open(event_path) as f:
                event = json.load(f)
            base_sha = event.get("before", "")

    if not base_sha:
        print("Error: BASE_SHA not set and could not be determined", file=sys.stderr)
        sys.exit(1)

    # Extract repo name (org/repo -> repo)
    repo_name = repo.split("/")[-1] if "/" in repo else repo

    print(f"Collecting metrics for {repo_name} ({base_sha[:8]}..{head_sha[:8]}) on {branch}")

    commits = get_merge_commits(base_sha, head_sha)
    print(f"Found {len(commits)} commits")

    if not commits:
        print("No commits to process")
        return

    summary = build_summary(repo_name, branch, commits)

    # Print breakdown
    for tool, stats in summary["breakdown"].items():
        print(f"  {tool}: {stats['commits']} commits, +{stats['lines_added']}/−{stats['lines_removed']} lines")

    # Write output
    with open(output_file, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"Output written to {output_file}")

    # Also set GitHub Actions output
    github_output = os.environ.get("GITHUB_OUTPUT", "")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"total_commits={len(commits)}\n")
            ai_commits = sum(
                s["commits"] for t, s in summary["breakdown"].items() if t != "human"
            )
            f.write(f"ai_commits={ai_commits}\n")
            f.write(f"human_commits={summary['breakdown'].get('human', {}).get('commits', 0)}\n")


if __name__ == "__main__":
    main()
